import '@fontsource-variable/plus-jakarta-sans';
import './bootstrap';
import Alpine from 'alpinejs';
import { filterStore, multiPilih } from './filter';
import { halamanDashboard } from './dashboard/halaman';
import { halamanPortofolio } from './portofolio';
import { halamanKualitas } from './kualitas';
import { grafikKurvaS, grafikPerbandingan } from './proyek';
import { petaSebaran } from './peta';
import { halamanRisiko } from './risiko';

window.Alpine = Alpine;
Alpine.store('filter', filterStore());
Alpine.data('multiPilih', multiPilih);
Alpine.data('halamanDashboard', halamanDashboard);
Alpine.data('halamanPortofolio', halamanPortofolio);
Alpine.data('halamanKualitas', halamanKualitas);
Alpine.data('grafikKurvaS', grafikKurvaS);
Alpine.data('grafikPerbandingan', grafikPerbandingan);
Alpine.data('petaSebaran', petaSebaran);
Alpine.data('halamanRisiko', halamanRisiko);
Alpine.start();
